name: TestRail Tests

on:
  schedule:
    - cron: '15 10 * * *'
    - cron: '20 10 * * *'
    - cron: '25 10 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose a browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge
          - safari
          - firefox
      suite:
        description: 'Choose a test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - api

jobs:
  api_suite:
    runs-on: windows-latest
    if: github.event.schedule == '15 10 * * *' || github.event.inputs.suite == 'api'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run API tests
        run: mvn -B clean test -Dsuite=api -Dbrowser=${{ github.event.inputs.browser || 'firefox' }}

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: target/allure-results

  smoke_suite:
    runs-on: windows-latest
    if: github.event.schedule == '20 10 * * *' || github.event.inputs.suite == 'smoke'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run Smoke tests
        run: mvn -B clean test -Dsuite=smoke -Dbrowser=${{ github.event.inputs.browser || 'chrome' }}

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: target/allure-results

  regression_suite:
    runs-on: windows-latest
    if: github.event.schedule == '25 10 * * *' || github.event.inputs.suite == 'regression'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run Regression tests
        run: mvn -B clean test -Dsuite=regression -Dbrowser=${{ github.event.inputs.browser || 'edge' }} 

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: target/allure-results
